### ISSUE TITLE
Bad attribute index

### ISSUE THREAD

**Issue by angelfmarcos** [Gurux/gurux.dlms.java#7]
Usign the library in order to read and Kamstrup Omnipower meter, I have a error reading Profile Generic because it has a column with attribute value index 255

In GXDLMSProfileGeneric.setValue(), the code 
`addCaptureObject(obj, ((Number) tmp[2]).intValue(), ((Number) tmp[3]).intValue());`

pass the attribute index -1 instead 255, which provocates a exception.

**Comment by gurux01** [comment]
Hi,

Can you send message trace to us by email. If they are using -1 or 255 we do not know what that means, because this is not standard way. I believe that this means that this item is skipped, but I'm not sure.

**Comment by angelfmarcos** [comment]
The Stacktrace is

`java.lang.RuntimeException: Invalid attribute index
	at gurux.dlms.objects.GXDLMSProfileGeneric.addCaptureObject(GXDLMSProfileGeneric.java:160)
	at gurux.dlms.objects.GXDLMSProfileGeneric.setValue(GXDLMSProfileGeneric.java:603)
	at gurux.dlms.GXDLMSClient.updateValue(GXDLMSClient.java:930)
	at com.smarkia.protocols.dlmscosem.layers.DlmsLayer.readObject(DlmsLayer.java:184)
	at com.smarkia.protocols.dlmscosem.devices.generic.GenericDlmsDevice.getData(GenericDlmsDevice.java:77)
	at com.smarkia.metricscollection.gateway.dlmscosem.service.DlmsCosemDeviceServiceImpl.getData(DlmsCosemDeviceServiceImpl.java:107)
	at com.smarkia.metricscollection.gateway.dlmscosem.data.reader.DlmsCosemGateway.getMeasureReadedValueList(DlmsCosemGateway.java:347)
	at com.smarkia.metricscollection.gateway.dlmscosem.data.reader.DlmsCosemGateway.fillMeasuresWithReadedValues(DlmsCosemGateway.java:246)
	at com.smarkia.metricscollection.gateway.reader.SmarkiaGateway.read(SmarkiaGateway.java:162)
	at com.smarkia.metricscollection.gateway.dlmscosem.data.reader.DlmsCosemGatewayTest.testConnectionHost2(DlmsCosemGatewayTest.java:357)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.MethodInvocationHelper$1.runTestMethod(MethodInvocationHelper.java:200)
	at org.springframework.test.context.testng.AbstractTestNGSpringContextTests.run(AbstractTestNGSpringContextTests.java:158)
	at org.testng.internal.MethodInvocationHelper.invokeHookable(MethodInvocationHelper.java:212)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:689)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:882)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1189)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:348)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:343)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:305)
	at org.testng.SuiteRunner.run(SuiteRunner.java:254)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)`

The problem happens when one object of the capture objects (columns) has a attribute index like 255. The method addCaptureObject receives -1 as attribute index and throws the exception.
